#!/bin/sh
#
# Copyright 2016 Gaël PORTAY <gael.portay@gmail.com>
#
# Licensed under the MIT license.
#
# See: https://wiki.archlinux.org/index.php/xrandr
#

DPDEVS="${*:-HDMI1 DP1}"
PREFIX=/usr/local
dir="$PREFIX/share/${0##*/}.d/"

event="disconnected"
for dpdev in $DPDEVS; do
	if ! xrandr | grep -q "$dpdev disconnected"; then
		event="connected"
		eval dppos=\${$dpdev:-right}
		break
	fi
	unset dpdev
done

echo event=$event
echo dpdev=$dpdev
echo dppos=$dppos
exit 1

if ! run-parts --exit-on-error --arg "$event" --arg "$dpdev" --arg "$dppos" "$dir/"; then
	echo "Warning: $dir: Halted!" >&2
fi

if [ "$event" = "disconnected" ]; then
	xrandr --output "LVDS1"  --auto --primary
#	xrandr --output "$dpdev" --off
else
	xrandr --output "$dpdev" --auto "--$dppos-of" "LVDS1" --primary
fi

if ! run-parts --exit-on-error --arg "$event" --arg "$dpdev" --arg "$dppos" "$dir/"; then
	echo "Warning: $dir: Halted!" >&2
fi
