#!/bin/sh
#
# Copyright 2016 Gaël PORTAY <gael.portay@gmail.com>
#
# Licensed under the MIT license.
#
# See: https://wiki.archlinux.org/index.php/xrandr
#

DPDEV="${1:-DP1}"
DPPOS="${2:-right}"
PREFIX=/usr/local
dir="$PREFIX/share/${0##*/}.d/"

if xrandr | grep -q "$DPDEV disconnected"; then
	event="disconnected"
else
	event="connected"
fi

if ! run-parts --exit-on-error --arg "$event" --arg "$DPDEV" --arg "$DPPOS" "$dir/"; then
	echo "Warning: $dir: Halted!" >&2
fi

if [ "$event" = "disconnected" ]; then
	xrandr --output "LVDS1"  --auto --primary
	xrandr --output "$DPDEV" --off
else
	xrandr --output "$DPDEV" --auto "--$DPPOS-of" "LVDS1" --primary
fi

if ! run-parts --exit-on-error --arg "$event" --arg "$DPDEV" --arg "$DPPOS" "$dir/"; then
	echo "Warning: $dir: Halted!" >&2
fi
