#!/bin/sh
#
# Copyright 2017 Gaël PORTAY <gael.portay@savoirfairelinux.com>
#
# Licensed under the MIT license.
#

/bin/mount -t proc  proc  /proc

/bin/mknod -m 666 /dev/null c 1 3
/bin/mknod -m 400 /dev/tty2 c 4 2
/bin/mknod -m 400 /dev/tty3 c 4 3
/bin/mknod -m 400 /dev/tty4 c 4 4
/bin/mknod -m 400 /dev/tty5 c 4 5
/bin/mknod -m 400 /dev/tty6 c 4 6
